<?xml version="1.0"?>
<package format="3">
  <name>mrosuam</name>
  <version>0.0.0</version>
  <description>The mrosuam package</description>

  <maintainer email="mdrummondstoyles@gmail.com">matt</maintainer>

  <license>Apache-2.0</license>
  
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  
  <export>
    <build_type>ament_cmake</build_type>

    <depend>rclcpp</depend>
    <depend>std_msgs</depend>
    <depend>geometry_msgs</depend>
    <depend>mavros</depend>
    <depend>mavros_msgs</depend>
    <depend>camera_ros</depend>
    
  </export>
  
</package>
